# Generated by Django 4.0.2 on 2024-07-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codemaster',
            fields=[
                ('classification', models.CharField(max_length=2)),
                ('code', models.IntegerField()),
                ('skillid', models.CharField(db_column='skillId', max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('createddate', models.CharField(db_column='createdDate', max_length=20)),
                ('updateddate', models.CharField(blank=True, db_column='updatedDate', max_length=20, null=True)),
            ],
            options={
                'db_table': 'CodeMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Engineerinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('neareststation', models.CharField(blank=True, db_column='nearestStation', max_length=20, null=True)),
                ('finaleducation', models.CharField(blank=True, db_column='finalEducation', max_length=30, null=True)),
                ('foreignnationality', models.IntegerField(blank=True, db_column='foreignNationality', null=True)),
            ],
            options={
                'db_table': 'EngineerInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projectinfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('jobtype', models.CharField(blank=True, db_column='jobType', max_length=255, null=True)),
                ('recruitmentnumbers', models.CharField(blank=True, db_column='recruitmentNumbers', max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=255, null=True)),
                ('clientname', models.CharField(blank=True, db_column='clientName', max_length=255, null=True)),
                ('workcontents', models.CharField(blank=True, db_column='workContents', max_length=255, null=True)),
                ('workprocess', models.CharField(blank=True, db_column='workProcess', max_length=255, null=True)),
                ('mustskill', models.CharField(blank=True, db_column='mustSkill', max_length=255, null=True)),
                ('passableskill', models.CharField(blank=True, db_column='passableSkill', max_length=255, null=True)),
                ('skilllevel', models.CharField(blank=True, db_column='skillLevel', max_length=255, null=True)),
                ('paymentunitprice', models.CharField(blank=True, db_column='paymentUnitPrice', max_length=255, null=True)),
                ('numberofinterviews', models.CharField(blank=True, db_column='numberOfInterviews', max_length=255, null=True)),
                ('foreignnationality', models.CharField(blank=True, db_column='foreignNationality', max_length=255, null=True)),
                ('bpallowed', models.CharField(blank=True, db_column='bpAllowed', max_length=255, null=True)),
                ('startdate', models.CharField(blank=True, db_column='startDate', max_length=255, null=True)),
                ('neareststation', models.CharField(blank=True, db_column='nearestStation', max_length=255, null=True)),
                ('telework', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ProjectInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skillinfo',
            fields=[
                ('id', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('skillid', models.CharField(db_column='skillId', max_length=6)),
                ('skillinfoid', models.CharField(db_column='skillInfoId', max_length=20, primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=20)),
                ('years', models.CharField(blank=True, max_length=5, null=True)),
                ('skilllevel', models.CharField(blank=True, db_column='skillLevel', max_length=1, null=True)),
            ],
            options={
                'db_table': 'SkillInfo',
                'managed': False,
            },
        ),
    ]
